### ISSUE TITLE
Icon path is wrong in linux install script

### ISSUE THREAD

**Issue by kolewu** [essej/sonobus#27]
The icon path used in the linux install script `Builds/LinuxMakefile/install.sh` is wrong. It should be `${PREFIX}/share/pixmaps`:
```diff
- mkdir -p ${PREFIX}/pixmaps
- cp  ../../images/sonobus_logo@2x.png ${PREFIX}/pixmaps/sonobus.png
+ mkdir -p ${PREFIX}/share/pixmaps
+ cp  ../../images/sonobus_logo@2x.png ${PREFIX}/share/pixmaps/sonobus.png
```

**Comment by essej** [comment]
Thanks, just committed that fix!

**Comment by strk** [comment]
Speaking of which, is there another logo for the *server* ? I think I saw it on windows but not on Linux, is this possible ?
