### ISSUE TITLE
Ubuntu studio locks up

### ISSUE THREAD

**Issue by JackCahn** [essej/sonobus#28]
Running Ubuntu studio 20.10 with current Sonobus build.  I am connected only 3-5 seconds and can hear others clearly, then screen freezes and silence.  Using USB Focusrite Scarlet. Jack settings using qjackctl are: USB, 48000Hz, 128frames, x2.  Audio settings in Sonobus: both input and output set to use "jack connection kit". Mic meter and test tone both work. 
Processor 2x AMD E1-1500 APU with Radeon HD Graphics. RAM 3.6G   Graphics processor AMD PALM.

The above is on an old box.  Have also installed Ubuntustudio on a newer laptop with a quad core intel I7 and there Sonobus connects for about 60 seconds before lock up.  I sure wish I could solve this, but end up beating my head on the desk :>)

**Comment by essej** [comment]
I wish I could reproduce this... sounds like something in the audio thread callback gets put into a crazy state and goes into a loop.  Does this only happen once connected to someone?

Perhaps trying to run this in a debugger will let you break out and find where it is stuck... do you have any experience with that kind of thing? I can try to walk you through it....

**Comment by JackCahn** [comment]
mea culpa essej. I DO NOT have freezing with the I7 laptop. It does drop audio at times while self adjusting the jitter buffer, but that is temporary.  And actually it is running JamulusOS.  I am going to replace that with Ubuntu Studio 20.10 and will post back later.  Sorry for any consternation I've caused, I believe the old AMD box has outlived its usefulness and had I read the instructions, I would have noted it was below par.

**Comment by JackCahn** [comment]
Also works flawlessly with Ubuntu studio 20.10.  Great project!
