### ISSUE TITLE
Request: Trim files saved in a specific directory

### ISSUE THREAD

**Issue by wolftune** [essej/sonobus#33]
in my case, I have the preference set to save recordings to ~/Music/Sonobus/ and that works, but the trim files are saved in just ~/Music/  EDIT: they are saved in whatever directory a file was in.

I don't want to clutter ~/Music/ with trim files. I'd rather they get saved in the same directory with recordings.

I could imagine a separate setting for where they go. I could imagine automatically making a "trims" directory within the general place Sonobus saves audio. I could also imagine using /tmp/ or some other temporary place with an option to save trims for later use. But just having them in their own reliable directory at all would make it easier to manage them.

**Comment by essej** [comment]
That just sounds like a bug... they should be going right next to the originals....

**Comment by essej** [comment]
I'm not able to reproduce this one either. What platform are you on?

**Comment by wolftune** [comment]
I'm on an Ubuntu-based system, but I just tested again. The actual issue is that the trim file is going wherever the original is. So, I don't want to clutter my directories with trim files based on wherever a file I opened happened to be.

So, I'm seeing reliably that the trim file is going in the same directory as the original, whatever and wherever that was. Instead, I want to have trim files go to a tmp or specified or Sonobus directory so that I can easily clear them out since I often don't want to keep them long-term.

**Comment by essej** [comment]
I see, usually I only assumed people would use the trim function for recorded files so it made sense to put them right next to the file itself (since it would make the most sense contextually). I suppose I could just open a Save file dialog when you hit the trim button, populated with the default location/filename and let you change it, but I tend to avoid as many file dialogs as possible when it comes to recording or editing workflows.

**Comment by wolftune** [comment]
I think *recording* and trimming it's sensible enough to save in the same spot. The funniness happens when opening an *existing* file and then trims get saved to wherever that is. The feature of opening existing files is obviously separate from the recording idea.

The main reason I liked trim with opening play-along stuff is because that enables more precision in setting the loops. It functions as a "zoom in" effectively. I actually don't want any trim file to get saved usually, I just want to zoom in.

**Comment by essej** [comment]
You can zoom in by dragging vertically on the waveform!

**Comment by wolftune** [comment]
Oh!! cool, I'll just close this!
