### ISSUE TITLE
RPI4 - Selected processor does not support 'yield' in ARM mode

### ISSUE THREAD

**Issue by electrautistic** [essej/sonobus#5]
Hello, very cool project !!!

I try to build on my Raspberry PI 4 and i got this error 

```
Compiling sync.cpp
/tmp/cc5GkAhk.s: Messages de l'assembleur:
/tmp/cc5GkAhk.s:29: Error: Selected processor does not support 'yield' in ARM mode
make: *** [Makefile:240: build/intermediate/Release/sync_c3d7827e.o] Error 1
```

**lscpu:**
Architecture:              armv7l
Byte Order:                Little Endian
CPU(s):                      4
On-line CPU(s) list:     0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):                   1
Vendor ID:                  ARM
Model:                        3
Model name:              Cortex-A72
Stepping:                    r0p3
CPU max MHz:          1500,0000
CPU min MHz:           600,0000
BogoMIPS:                108.00
Flags:                        half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32

**OS**
Raspberry Pi OS (32-bit) with desktop

Thank you

**Comment by essej** [comment]
Thanks!  Yeah, I need to fix the build for 32bit RPi4... it works cleanly on Ubuntu 64bit on the Rpi4. I'll flash a rasppiOS 32bit sdcard and fix that soon!

**Comment by essej** [comment]
In the meantime here is a hackaround patch someone made, but I want to see if there is cleaner fix:

diff --git a/deps/aoo/lib/src/sync.cpp b/deps/aoo/lib/src/sync.cpp
index 10cd51f..ddd4fab 100644
--- a/deps/aoo/lib/src/sync.cpp
+++ b/deps/aoo/lib/src/sync.cpp
@@ -18,6 +18,8 @@
 // ARM
 #elif defined(__arm__) || defined(_M_ARM) || defined(__aarch64__)
   #define CPU_ARM
+/* -CA fix for compile error on raspberry pi */
+  #include <thread>
 #else
 // fallback
   #include <thread>
@@ -28,8 +30,10 @@ namespace aoo {
 void pause_cpu(){
 #if defined(CPU_INTEL)
     _mm_pause();
+/* -CA fix for compile error on raspberry pi
 #elif defined(CPU_ARM)
     __asm__ __volatile__("yield");
+ */
 #else // fallback
     std::this_thread::sleep_for(std::chrono::microseconds(0));
 #endif

**Comment by electrautistic** [comment]
wow !!!! 4 minutes for answer !   you are awesome !!!!

**Comment by essej** [comment]
OK, latest git should now build clean on Raspberry Pi OS 32 bit.

**Comment by electrautistic** [comment]
I highly recommend this great project !!!
Thanks
