### ISSUE TITLE
A question about jack1

### ISSUE THREAD

**Issue by IronBug** [essej/sonobus#52]
It's not an issue. Just a question: why jack1?
jack1 was used decades ago. is there any special reason for this choice or it's just a rudiment of past times?
are there any problems with moving to jack2?

I'm a C/C++ programmer with a lot of experience, also an amateur musician and I use Linux. I discovered sonobus and was glad but jack1 seems too outdated to me. I could try to port the code to jack2. but I wanted to ask this question before. maybe there're some principal problems with it.

**Comment by jalalsfs** [comment]
That's only if you use Snap way to install it, but if you compile it from the source, or use another package manager it should be fine with current jackd (2).

**Comment by essej** [comment]
Correct, this was a Snap build limitation, for whatever reason. It works fine with both if you build it for yourself. One day I’ll distribute normal packages too.

**Comment by IronBug** [comment]
ah, ok then. thanks for the answer.
I gonna make a package for Void Linux and test it with musl (I use musl based build).
