### ISSUE TITLE
When typing into track name text box, if hold key 't' and then press another key, then textbox looses focus and mute all engages and loose any inputted text

### ISSUE THREAD

**Issue by ericfont** [essej/sonobus#62]

**Comment by essej** [comment]
Yes, this is the key binding for the “push-to-talk” feature. It has no modifier on purpose, but it shouldn’t be activating when in an active text editing. Seems to be Linux specific, I think

**Comment by ericfont** [comment]
it happens on windows also.

Funny thing it doesn't seem to happen with other shortcut keys such as 'm' for mute.

**Comment by ericfont** [comment]
I'm copying below the console output when run in debug mode where I'm pressing a t when inside a text box and then press a second letter d:

```
T press
uninviting peer 1 source 1
Got key: t  isdown: 1 keycode: 116 pcode: 112
RESIZED to 1062 708
UNDERRUN resampler avail 50  readsamp: 96
Got source state event from 136.49.96.179:52385 -- 0
Got key: d  isdown: 1 keycode: 100 pcode: 112
T release
inviting peer 1 source 1
RESIZED to 1062 708
PCM settings: nchannels = 6, blocksize = 48, samplerate = 44100, bitdepth = 2
reset source queues to 5 buffers
decode failed nsamples: 288 audioqavail: 2
wrote 1 empty blocks for sink xrun
fading in block
Got source format event from 136.49.96.179:52385  1  channels: 6
Got layout userformat for peer: <?xml version="1.0" encoding="UTF-8"?>

<ChannelLayouts>
  <Layout chanstart="0" numchan="1" name="guitar - di" span1="-1.0" span2="1.0">
    <StereoPanners>
      <Panner pan="0.0"/>
    </StereoPanners>
  </Layout>
  <Layout chanstart="1" numchan="1" name="voice" span1="-1.0" span2="1.0">
    <StereoPanners>
      <Panner pan="0.01999999955296516"/>
    </StereoPanners>
  </Layout>
  <Layout chanstart="2" numchan="1" name="bass" span1="-1.0" span2="1.0">
    <StereoPanners>
      <Panner pan="0.0"/>
    </StereoPanners>
  </Layout>
  <Layout chanstart="3" numchan="1" name="guitar - amp" span1="-1.0" span2="1.0">
    <StereoPanners>
      <Panner pan="-0.01999999955296516"/>
    </StereoPanners>
  </Layout>
  <Layout chanstart="4" numchan="2" name="spdif" span1="-1.0" span2="1.0">
    <StereoPanners>
      <Panner pan="0.0"/>
      <Panner pan="0.0"/>
    </StereoPanners>
  </Layout>
</ChannelLayouts>

Restoring layout userformat for peer
```

**Comment by ericfont** [comment]
the bug does not happen for the following sequence:

1. press t
2. press d
3. release t
4. release d

However it does happen with the following sequence:

1. press t
2. press d 
3. release d
(at which point the mute-all toggle happens and I loose textbox focus)

**Comment by ericfont** [comment]
I'm noticing with I try the first sequence above, it doesn't produce any console output.

However when I run the second sequence above, then I get the following console output upon releasing the d:
```
T press
RESIZED to 1062 708
```

And then the following console output upon releasing the t:
```
T release
RESIZED to 1062 708
```

**Comment by ericfont** [comment]
Those code for that T press/release detection is here:

https://github.com/essej/sonobus/blob/a7cfde9c78ab77661044fd593fcd24d680b0c291/Source/SonobusPluginEditor.cpp#L3692-L3717

**Comment by ericfont** [comment]
very suspicious part is:

`pttdown = KeyPress::isKeyCurrentlyDown('T');`

**Comment by ericfont** [comment]
I'm gonna see what happens if test for text box focus and if so return zero immediately before that code snippet.

**Comment by ericfont** [comment]
I'm not familiar-enough to know best approach.  If had a simple if to test if a textbox is being edited (or if no text editor has focus), then could simply exit out of SonobusAudioProcessorEditor::keyStateChanged() early when true.

I am also have no idea how "PushToTalkButton" works.

**Comment by ericfont** [comment]
just looking again in debugger, and I notice when releasing d in the second sequence while still holding t, that isKeyCurrentlyDown('T') incorrectly returns as false:

https://github.com/essej/sonobus/blob/a9b1ad3de00a952a45ae112c5d5139e43237d880/Source/SonobusPluginEditor.cpp#L2969

So it almost sounds like that might be a bug in https://docs.juce.com/master/classKeyPress.html#a94c2aecc867e4dba1382c31c377523d2 implementation

**Comment by ericfont** [comment]
I'm also noticing with breakpoint on that line, that SonobusAudioProcessorEditor::keyStateChanged doesn't get called when pressing and t and then d when focus in in the text box, but that function does get called on the release of d.  So I guess the real problem is that that function is even called in the first place upon the release of d...cause it simply shouldn't be called upon any textbox keypresses.

**Comment by ericfont** [comment]
maybe https://docs.juce.com/master/classKeyboardFocusTraverser.html will be helpful with setExplicitFocusOrder, if can apply so the input group nameLabel gets focus order before the main widget.

**Comment by ericfont** [comment]
or rather stop any letter key events from propagating.

**Comment by ericfont** [comment]
according to discord chat, the bug does happen on MAC too.  So seems all platforms.  I've also verified happens as a VST3 in Ardour Linux.

**Comment by ericfont** [comment]
see PR #65 for my attempted fix
