### ISSUE TITLE
Send stereo sometimes sends dual mono

### ISSUE THREAD

**Issue by Zipdox** [essej/sonobus#69]
I'm reporting this on behalf of a friend on Windows 10 with ASIO. Unfortunately this bug is intermittent and hard to reproduce.

Basically sometimes when you select "Send Stereo" or "Math # Inputs", it the sending client will send stereo, but the receiving end will receive dual mono. We were unable to find a way to reproduce this issue and as far as we know it's random.

**Comment by essej** [comment]
This issue was fixed in the last few says (as it presented in the new beta) in 1.3.17. Basically all bugs from the "release" version are pointless as so much has changed in the soon to be released 1.4.0 (when i make the beta the stable)

**Comment by Zipdox** [comment]
Ok, good to hear.
